---
- name: remove tripleo-ci if exist
  file: path=/home/stack/tripleo-ci state=absent

- name: check or install required packages
  become: true
  yum: name={{ item }} state=latest
  with_items:
    - epel-release

- name: check or install required packages
  become: true
  yum: name={{ item }} state=latest
  with_items:
    - git-review

# TODO: remove the patch review with zuul parameters
- name: clone tripleo ci repo on the undercloud vms
  shell: >
    git clone https://github.com/openstack-infra/tripleo-ci.git;
    pushd tripleo-ci;
    git remote add gerrit https://review.openstack.org/openstack/tripleo-ci;
    git fetch --all;
    git review -d I085a7134bbbf4086c1793d405b400e19eac6b003

- name: create ci script
  template:
    src: "{{ ci_script }}"
    dest: "/home/stack/ci.sh"
    mode: 0755

- name: run ci script
  shell: >
    /home/stack/ci.sh > ci.log 2>&1
